
VAGRANTFILE_API_VERSION = "2"


$scriptfirst = <<-SCRIPT
  yum -y update
  yum -y install epel-release vim

  cat > /etc/yum.repos.d/ARM.repo << EOF
  [ARMP6]
  name=ARM Production RH6 Repository
  baseurl=http://yum.arm.gov/prod6
  gpgcheck=0
  EOF

  yum -y install netcdf-devel dsdb-sqlite dsdb-python_lib unzip udunits2 man afl-libcds3 > /var/log/adiinstall.log 2>&1
  yum -y groupinstall adi6 >> /var/log/adiinstall.log 2>&1


  cat > /etc/ld.so.conf.d/adi_libs.conf << EOF
  /usr/lib64
  /apps/ds/lib64
  /apps/ds/lib
  EOF

  sudo ldconfig
  sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions"

  SCRIPT

$script = <<-SCRIPT
  cat >> ~/.bashrc << EOF

  export ADI_HOME=/home/vagrant/adi_home
  export SHARE_HOME=/vagrant
  
  export PATH=/apps/base/python2.7/bin:$PATH:$HOME/bin:/apps/base/bin:/apps/ds/bin:/apps/bin:/apps/tool/bin:$HOME/dev/process/vap/bin:/usr/lib64:/apps/ds/lib64
  export DSDB_DATA=/apps/ds
  export PERLLIB=/apps/ds/lib
  export DSDB_HOME=/apps/ds
  export VAP_HOME=$ADI_HOME/dev/vap
  
  export DATA_HOME=$SHARE_HOME/data
  export DATASTREAM_DATA=$DATA_HOME/adi_example1/datastream
  export CONF_DATA=$DATA_HOME/adi_example1/conf
  export LOGS_DATA=$DATA_HOME/adi_example1/logs
  
  export CPATH=$CPATH:/apps/ds/include
  export LD_LIBRARY_PATH=$:/apps/ds/lib64
  export PATH=$PATH:/apps/base/python2.7/bin:$ADI_HOME/bin:/apps/base/bin:/apps/ds/bin:/apps/bin:/apps/tool/bin:$ADI_HOME/dev/process/vap/bin:/usr/lib64
  export PATH=/home/vagrant/anaconda2/bin:$PATH:$VAP_HOME/bin
  EOF

  source ~/.bashrc
  wget -N https://engineering.arm.gov/~whao/adi_vm_home.tar.gz
  tar -xzvf adi_vm_home.tar.gz
  rm adi_vm_home.tar.gz
  mv ~/adi_home/data /vagrant/data
  mkdir -p /vagrant/data/db/sqlite
  mkdir -p /home/vagrant/adi_home/data/db/sqlite
  cp /apps/ds/conf/sqlite/20151006.185806.dsdb.sqlite ~/adi_home/data/db/sqlite/dsdb.sqlite
  cp /apps/ds/conf/sqlite/20151006.185806.dsdb.sqlite /vagrant/data/db/sqlite/dsdb.sqlite


  cat > ~/.db_connect << EOF
  dsdb_data sqlite  /home/vagrant/adi_home/data/db/sqlite/dsdb.sqlite
  dsdb_read sqlite /home/vagrant/adi_home/data/db/sqlite/dsdb.sqlite
  EOF


  cd ~/adi_home/dev/vap/src/adi_example1/process_dod_defs
  db_import_process -a dsdb_data -fmt json adi_example1.json
  db_load_dod -a dsdb_data cpc.json
  db_load_dod -a dsdb_data met.json
  cd ../
  cp linux_makefile Makefile
  make clean
  make
  cd ~/
  rm -rf adi_home.tar.gz adi_home.tar.gz.1 adi-macosx-master adi-python-1.1.tar master.zip

  wget -N -r -O adi-python.tar https://engineering.arm.gov/~gaustad/adi-python-1.1.tar
  tar -xvf adi-python.tar
  rm adi-python.tar

  wget -N -O anaconda.sh https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda2-2.4.1-Linux-x86_64.sh
  bash anaconda.sh -b
  rm anaconda.sh

  export PATH=/home/vagrant/anaconda2/bin:$PATH
  cd ~/py_lib
  python setup.py build_ext -L/apps/ds/lib64 
  python setup.py install --user

  SCRIPT




Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"
  config.vm.synced_folder ".", "/vagrant"
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination:"~/.ssh/authorized_keys"
  config.ssh.forward_agent = true

  config.vm.provision :shell, inline: $scriptfirst
  config.vm.provision :shell, inline: $script, privileged: false
end
