
VAGRANTFILE_API_VERSION = "2"


$script = <<-SCRIPT
  cat /vagrant/env_vars >> /home/vagrant/.bashrc
  source ~/.bashrc
  wget -N https://engineering.arm.gov/~whao/adi_vm_home.tar.gz
  tar -xzvf adi_vm_home.tar.gz
  #mv /vagrant/example_1_makefile_corrected  /home/vagrant/adi_home/dev/vap/src/adi_example1/Makefile
  cp -r ~/adi_home/data /vagrant/data
  mkdir -p /vagrant/data/db/sqlite
  mkdir -p /home/vagrant/adi_home/data/db/sqlite
  cp /apps/ds/conf/sqlite/20151006.185806.dsdb.sqlite ~/adi_home/data/db/sqlite/dsdb.sqlite
  cp /apps/ds/conf/sqlite/20151006.185806.dsdb.sqlite /vagrant/data/db/sqlite/dsdb.sqlite
  cp /vagrant/.db_connect ~/
  cd ~/adi_home/dev/vap/src/adi_example1/process_dod_defs
  db_import_process -a dsdb_data -fmt json adi_example1.json
  db_load_dod -a dsdb_data cpc.json
  db_load_dod -a dsdb_data met.json
  cd ../
  cp linux_makefile Makefile
  make clean
  make
  cd ~/
  rm -rf adi_home.tar.gz adi_home.tar.gz.1 adi-macosx-master adi-python-1.1.tar master.zip
  wget -N -r -O adi-macosx.zip https://github.com/ARM-DOE/adi-macosx/archive/master.zip
  unzip adi-macosx.zip
  mv adi-macosx-master adi-master 
  rm adi-macosx.zip
  wget -N -r -O adi-python.tar https://engineering.arm.gov/~gaustad/adi-python-1.1.tar
  tar -xvf adi-python.tar
  rm adi-python.tar
  bash /vagrant/anaconda.sh -b
  export PATH=/home/vagrant/anaconda2/bin:$PATH
  cd ~/py_lib
  python setup.py build_ext -L/apps/ds/lib64 
  python setup.py install --user

  SCRIPT




Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision :shell, inline: "sudo cp /vagrant/ARM.repo /etc/yum.repos.d/ARM.repo"
  config.vm.provision :shell, inline: "sudo yum -y update"
  config.vm.provision :shell, inline: "sudo yum -y install epel-release vim"
  config.vm.provision :shell, inline: "sudo yum -y groupinstall adi6"
  config.vm.provision :shell, inline: "sudo yum -y install netcdf-devel dsdb-sqlite dsdb-python_lib unzip udunits2 man afl-libcds3"
  config.vm.provision :shell, inline: "sudo cp /vagrant/adi_libs.conf /etc/ld.so.conf.d/"
  config.vm.provision :shell, inline: "sudo ldconfig"
  config.vm.provision :shell, inline: "sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions"

  config.vm.provision :shell, inline: $script, privileged: false
end
